import img from '../images/movies-card__img.png'
export const constantMovies = [
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 1,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 2,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 3,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 4,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 5,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 6,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 7,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 8,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 9,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 10,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 11,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 12,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 13,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 14,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 15,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 16,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 17,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 18,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 19,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 20,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 21,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 22,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 23,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 24,
  },
]

export const constantMoviesSaved = [
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 1,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 2,
  },
  {
    name: '33 слова о дизайне',
    image: img,
    duration: 102,
    trailerLink: "https://youtu.be/JORGN8rUjyQ?si=ZtHqHiEzcTUQ60b_",
    movieId: 3,
  }, 
]